import { Webhook } from "npm:standardwebhooks@1";

const TWOFACTOR_API_KEY =
  Deno.env.get("TWOFACTOR_API_KEY");

const SEND_SMS_HOOK_SECRET =
  Deno.env.get("SEND_SMS_HOOK_SECRET");

Deno.serve(async (req) => {
  try {
    // --------------------------------------------------
    // Only POST is allowed
    // --------------------------------------------------

    if (req.method !== "POST") {
      return new Response(
        JSON.stringify({
          error: "Method not allowed",
        }),
        {
          status: 405,
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    }


    // --------------------------------------------------
    // Check required secrets
    // --------------------------------------------------

    if (!TWOFACTOR_API_KEY) {
      console.error(
        "TWOFACTOR_API_KEY is not configured"
      );

      return new Response(
        JSON.stringify({
          error: "SMS provider is not configured",
        }),
        {
          status: 500,
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    }


    if (!SEND_SMS_HOOK_SECRET) {
      console.error(
        "SEND_SMS_HOOK_SECRET is not configured"
      );

      return new Response(
        JSON.stringify({
          error: "SMS hook secret is not configured",
        }),
        {
          status: 500,
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    }


    // --------------------------------------------------
    // Read the raw body
    // IMPORTANT:
    // Signature verification must use the raw body.
    // --------------------------------------------------

    const payload = await req.text();

    const headers = Object.fromEntries(
      req.headers.entries()
    );


    // --------------------------------------------------
    // Verify Supabase Auth Hook signature
    // --------------------------------------------------

    const hookSecret =
      SEND_SMS_HOOK_SECRET.replace(
        "v1,whsec_",
        ""
      );

    const webhook =
      new Webhook(hookSecret);

    let event: any;

    try {
      event = webhook.verify(
        payload,
        headers
      );
    } catch (error) {
      console.error(
        "Invalid Supabase hook signature"
      );

      return new Response(
        JSON.stringify({
          error: "Invalid hook signature",
        }),
        {
          status: 401,
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    }


    // --------------------------------------------------
    // Extract phone + OTP generated by Supabase
    // --------------------------------------------------

    const phone =
      event?.user?.phone;

    const otp =
      event?.sms?.otp;


    if (!phone || !otp) {
      console.error(
        "Missing phone number or OTP in Supabase hook payload"
      );

      return new Response(
        JSON.stringify({
          error:
            "Missing phone number or OTP",
        }),
        {
          status: 400,
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    }


    // --------------------------------------------------
    // T&M currently uses Indian +91 numbers
    //
    // Supabase:
    // +919582013176
    //
    // 2Factor:
    // 9582013176
    // --------------------------------------------------

    // --------------------------------------------------
// Normalize Indian phone number
// --------------------------------------------------

const digitsOnly = String(phone).replace(/\D/g, "");

let phoneNumber = digitsOnly;

// +91XXXXXXXXXX / 91XXXXXXXXXX
if (phoneNumber.length === 12 && phoneNumber.startsWith("91")) {
  phoneNumber = phoneNumber.slice(2);
}

// Already 10 digits
if (phoneNumber.length !== 10) {
  console.error(
    "Invalid Indian phone number format:",
    phone
  );

  return new Response(
    JSON.stringify({
      error: "Invalid Indian phone number",
    }),
    {
      status: 400,
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
}
    // --------------------------------------------------
    // Send Supabase-generated OTP through 2Factor
    // --------------------------------------------------

    const twoFactorUrl =
      `https://2factor.in/API/V1/` +
      `${encodeURIComponent(TWOFACTOR_API_KEY)}` +
      `/SMS/` +
      `${encodeURIComponent(phoneNumber)}` +
      `/` +
      `${encodeURIComponent(otp)}`;


    const response =
      await fetch(
        twoFactorUrl,
        {
          method: "POST",
        }
      );


    const responseText =
      await response.text();


    // --------------------------------------------------
    // HTTP-level failure
    // --------------------------------------------------

    if (!response.ok) {
      console.error(
        "2Factor HTTP error:",
        response.status
      );

      return new Response(
        JSON.stringify({
          error:
            "2Factor SMS request failed",
        }),
        {
          status: 502,
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    }


    // --------------------------------------------------
    // Parse 2Factor response
    // --------------------------------------------------

    let providerResponse: any;

    try {
      providerResponse =
        JSON.parse(
          responseText
        );
    } catch {
      providerResponse = null;
    }


    // --------------------------------------------------
    // 2Factor application-level failure
    // --------------------------------------------------

    if (
      providerResponse &&
      providerResponse.Status &&
      providerResponse.Status !==
        "Success"
    ) {
      console.error(
        "2Factor rejected SMS:",
        providerResponse.Status
      );

      return new Response(
        JSON.stringify({
          error:
            "2Factor rejected the SMS request",
        }),
        {
          status: 502,
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    }


    // --------------------------------------------------
    // SUCCESS
    //
    // Supabase Auth expects HTTP 200 from the hook.
    // --------------------------------------------------

    return new Response(
  JSON.stringify({}),
  {
    status: 200,
    headers: {
      "Content-Type": "application/json",
    },
  }
);

  } catch (error) {

    console.error(
      "send-auth-sms error:",
      error
    );

    return new Response(
      JSON.stringify({
        error:
          "Failed to send authentication SMS",
      }),
      {
        status: 500,
        headers: {
          "Content-Type": "application/json",
        },
      }
    );
  }
});